// tui_dashboard.go — the per-project menu ("Projects" → select one).
// Every entry reuses either the generic fileScreen (tui_fileview.go),
// the directory-listing screen (tui_reports.go), or the dedicated jobs
// screen (tui_jobs.go) — nothing project-dashboard-specific is
// implemented here beyond wiring up the right path for this project.
package main

import (
	"os"

	tea "github.com/charmbracelet/bubbletea"

	"mova.local/core"
)

func newProjectDashboard(app *tuiApp, project string) tuiScreen {
	fa := core.NewFileAdapter(app.root)
	proj, _ := fa.GetProject(project) // proj may be nil below if project.json is malformed — reports/jobs entries degrade gracefully

	dir := projectDir(app.root, project)
	items := []menuItem{
		{
			title: "project.json", desc: "Project configuration",
			onSelect: func() tea.Cmd {
				return tuiPush(newFileScreen(app, project+"/project.json", projectJSONPath(app.root, project), true))
			},
		},
		{
			title: "memory.md", desc: "Project active memory",
			onSelect: func() tea.Cmd {
				return tuiPush(newFileScreen(app, project+"/memory.md", memoryMDPath(app.root, project), true))
			},
		},
		{
			title: "Jobs", desc: "View and run scheduled jobs for this project",
			onSelect: func() tea.Cmd { return tuiPush(newJobsScreen(app, project)) },
		},
	}

	repo := app.root
	if proj != nil {
		repo = repoDir(app.root, proj.Repo)
	}
	items = append(items, menuItem{
		title: "Reports", desc: "Files generated by jobs (\"save\" action)",
		onSelect: func() tea.Cmd { return tuiPush(newDirListScreen(app, project+" — reports", repo+"/reports")) },
	})

	if _, err := os.Stat(dir + "/memory-archive"); err == nil {
		items = append(items, menuItem{
			title: "Archived memory", desc: "Entries archived by memory_archive",
			onSelect: func() tea.Cmd {
				return tuiPush(newDirListScreen(app, project+" — archived memory", dir+"/memory-archive"))
			},
		})
	}

	items = append(items, menuItem{
		title: "Execution history", desc: "mova-budget-report.md and mova-token-history.json",
		onSelect: func() tea.Cmd { return tuiPush(newHistoryMenu(app, project)) },
	})

	return newMenuScreen(project, items, "")
}

// newHistoryMenu shows whichever of the two execution-history files
// this project actually has (both are optional — created the first
// time `mova budget`/a job's "budget" action or real chat usage runs).
func newHistoryMenu(app *tuiApp, project string) tuiScreen {
	dir := projectDir(app.root, project)
	var items []menuItem
	candidates := []string{"mova-budget-report.md", "mova-token-history.json"}
	for _, name := range candidates {
		full := dir + "/" + name
		if _, err := os.Stat(full); err == nil {
			items = append(items, menuItem{
				title: name, desc: full,
				onSelect: func() tea.Cmd { return tuiPush(newFileScreen(app, name, full, false)) },
			})
		}
	}
	if len(items) == 0 {
		items = append(items, menuItem{title: "(no history yet)", desc: "Run `mova budget " + project + "` or a job's \"budget\" action to generate it"})
	}
	return newMenuScreen(project+" — history", items, "")
}